saltToTaste/views/main.py
import os
from datetime import datetime
from flask import current_app, Blueprint, render_template, request, send_file, safe_join, abort, session, url_for, redirect, flash, send_from_directory
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.utils import secure_filename
from saltToTaste.extensions import db
from saltToTaste.models import Recipe, Tag, Direction, Ingredient, Note
from saltToTaste.forms import RecipeForm
from saltToTaste.search_handler import search_parser
from saltToTaste.recipe_handler import add_recipe_file
from saltToTaste.database_handler import get_recipes, get_recipe_by_title_f, add_recipe
from saltToTaste.parser_handler import argparser_results

argument = argparser_results()
DATA_DIR = os.path.abspath(argument['DATA_DIR'])

main = Blueprint('main', __name__)

@main.route("/", methods=['GET', 'POST'])
def index():
    recipes = sorted(get_recipes(), key = lambda i: i['title'])

    if request.method == 'POST':
        search_data = request.form.getlist('taggles[]')
        if search_data:
            results = search_parser(search_data)
            return render_template("index.html", recipes=results)

    return render_template("index.html", recipes=recipes)

@main.route("/recipe/<string:recipe_link>")
def recipe(recipe_link):
    recipe = get_recipe_by_title_f(recipe_link)

    return render_template("recipe.html", recipe=recipe)

@main.route("/download/<path:filename>")
# @login_required
def download_recipe(filename):
    filename = filename.lower()
    safe_path = safe_join(current_app.config["RECIPE_FILES"], filename)
    try:
        return send_file(safe_path, as_attachment=True, attachment_filename=filename)
    except FileNotFoundError:
        abort(404)

@main.route("/image/<path:filename>", methods=['GET'])
def image_path(filename):
    return send_from_directory(current_app.config["RECIPE_IMAGES"], filename)

@main.route("/add", methods=['GET', 'POST'])
def add():
    form = RecipeForm()

    if form.validate_on_submit():
        title_formatted = form.title.data.replace(" ", "_").lower()
        image = form.image.data

        if image:
            image_extension = image.filename.rsplit('.', 1)[1].lower()
            image.filename = f'{title_formatted}.{image_extension}'
            filename = secure_filename(image.filename)
            image.save(os.path.join(current_app.config['RECIPE_IMAGES'], filename))
        else:
            filename = None

        tags = form.tags.data.split(',')

        recipe = {
            'layout' : form.layout.data or 'recipe',
            'title' : form.title.data,
            'formatted_title' : title_formatted,
            'image' : filename,
            'imagecredit' : form.image_credit.data, # this is the link to image to download
            'tags' : [tag.strip(' ') for tag in tags],
            'source' : form.source.data,
            'prep' : form.prep.data,
            'cook' : form.cook.data,
            'ready' : form.ready.data,
            'servings' : form.servings.data,
            'calories' : form.calories.data,
            'description' : form.description.data,
            'ingredients' : form.ingredients.data,
            'directions' : form.directions.data,
            'notes' : form.notes.data,
            'filename' : f'{title_formatted}.txt'
        }

        # add_recipe_file(recipe)
        # recipe['last_modified'] = datetime.fromtimestamp(os.stat(f'{DATA_DIR}/_recipes/{recipe["filename"]}').st_mtime)
        # add_recipe(recipe)

        if form.save.data:
            return redirect(url_for('main.recipe', recipe_link=title_formatted))
        if form.save_and_add.data:
            flash(f'Recipe {form.title.data} saved.', 'success')
            return redirect(url_for("main.add"))

    return render_template("add.html", form=form)

saltToTaste/templates/add.html
{% extends "layout.html" %}

{% block title_container %}
<title>Salt To Taste</title>
{% endblock %}

{% block body_container %}
  <div class="container mt-1">
    <h1 class="form-title">Add Recipe</h1>
    <form class="needs-validation" method="post" enctype=multipart/form-data action="/add" novalidate>
      {{ form.csrf_token }}
      <div class="form-row d-none">
        <div class="form-group col-12">
          <label for="form-recipe-layout">Layout:</label>
          <select class="form-control" id="form-recipe-layout" name="layout">
            <option value="recipe">Recipe</option>
          </select>
        </div>
      </div>
      <div class="form-row row-cols-1 row-cols-md-2">
        <div class="col order-2 order-md-1">
          <div class="form-row">
            <div class="form-group col-12">
              <!-- <label for="form-recipe-name">Name</label> -->
              <input type="text" class="form-control {% if form.title.errors %}is-invalid{% endif %}" id="form-recipe-name" name="title" placeholder="Name" {% if form.title.data %}value="{{ form.title.data }}"{% endif %}>
              <div class="invalid-feedback">
                {% if form.title.errors %}
                {{ form.title.errors[0] }}
                {% endif %}
              </div>
            </div>
            <div class="form-group col-12 col-md">
              <!-- <label for="form-recipe-source">Source</label> -->
              <input type="text" class="form-control {% if form.source.errors %}is-invalid{% endif %}" id="form-recipe-source" name="source" placeholder="Source" {% if form.source.data %}value="{{ form.source.data }}"{% endif %}>
              <div class="invalid-feedback">
                {% if form.source.errors %}
                {{ form.source.errors[0] }}
                {% endif %}
              </div>
            </div>
            <div class="form-group col-12 col-md">
              <!-- <label for="form-recipe-tags">Tags</label> -->
              <input type="text" class="form-control {% if form.tags.errors %}is-invalid{% endif %}" id="form-recipe-tags" name="tags" placeholder="Tags" {% if form.tags.data %}value="{{ form.tags.data }}"{% endif %}>
              <div class="invalid-feedback">
                {% if form.tags.errors %}
                {{ form.tags.errors[0] }}
                {% endif %}
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-12 col-md">
              <!-- <label for="form-recipe-prep">Prep Time</label> -->
              <input type="text" class="form-control {% if form.prep.errors %}is-invalid{% endif %}" id="form-recipe-prep" name="prep" placeholder="Prep Time {% if form.prep.data %}value="{{ form.prep.data }}"{% endif %}">
              <div class="invalid-feedback">
                {% if form.prep.errors %}
                {{ form.prep.errors[0] }}
                {% endif %}
              </div>
            </div>
            <div class="form-group col-12 col-md">
              <!-- <label for="form-recipe-cook">Cook Time</label> -->
              <input type="text" class="form-control {% if form.cook.errors %}is-invalid{% endif %}" id="form-recipe-cook" name="cook" placeholder="Cook Time" {% if form.cook.data %}value="{{ form.cook.data }}"{% endif %}>
              <div class="invalid-feedback">
                {% if form.cook.errors %}
                {{ form.cook.errors[0] }}
                {% endif %}
              </div>
            </div>
            <div class="form-group col-12 col-md">
              <!-- <label for="form-recipe-ready">Ready In</label> -->
              <input type="text" class="form-control {% if form.ready.errors %}is-invalid{% endif %}" id="form-recipe-ready" name="ready" placeholder="Ready In" {% if form.ready.data %}value="{{ form.ready.data }}"{% endif %}>
              <div class="invalid-feedback">
                {% if form.ready.errors %}
                {{ form.ready.errors[0] }}
                {% endif %}
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-12 col-md">
              <!-- <label for="form-recipe-servings">Servings</label> -->
              <input type="text" class="form-control {% if form.servings.errors %}is-invalid{% endif %}" id="form-recipe-servings" name="servings" placeholder="Servings" {% if form.servings.data %}value="{{ form.servings.data }}"{% endif %}>
              <div class="invalid-feedback">
                {% if form.servings.errors %}
                {{ form.servings.errors[0] }}
                {% endif %}
              </div>
            </div>
            <div class="form-group col-12 col-md">
              <!-- <label for="form-recipe-calories">Calories</label> -->
              <input type="text" class="form-control {% if form.calories.errors %}is-invalid{% endif %}" id="form-recipe-calories" name="calories" placeholder="Calories" {% if form.calories.data %}value="{{ form.calories.data }}"{% endif %}>
              <div class="invalid-feedback">
                {% if form.calories.errors %}
                {{ form.calories.errors[0] }}
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="col order-1 order-md-2 pb-3">
          <div class="d-flex flex-column w-100 h-100 align-self-stretch align-items-stretch justify-content-center image-upload-container">
            <div class="position-relative flex-grow-1 {% if form.image.errors %}is-invalid{% endif %}">
              <div class="position-absolute d-flex w-100 h-100 align-items-center justify-content-center">
                <label class="btn add-image-btn"> Choose image...
                  <input type="file" class="custom-file-input d-none" id="form-recipe-image" name="image">
                </label>
              </div>
              <div class="position-absolute w-100 h-100 border rounded image-container {% if form.image.errors %}invalid-image{% endif %}" id="selected-image"></div>
            </div>
            <div class="invalid-feedback">
              {% if form.image.errors %}
              {{ form.image.errors[0] }}
              {% endif %}
            </div>
          </div>

        </div>
      </div>
      <div class="form-group">
        <!-- <label for="form-recipe-description">Description</label> -->
        <textarea class="form-control {% if form.description.errors %}is-invalid{% endif %}" id="form-recipe-description" rows="3" name="description" placeholder="Description" {% if form.description.data %}value="{{ form.description.data }}"{% endif %}></textarea>
        <div class="invalid-feedback">
          {% if form.description.errors %}
          {{ form.description.errors[0] }}
          {% endif %}
        </div>
      </div>
      <div class="form-group">
        <label>Notes</label>
        <div>
          <button class="btn btn-success add-note" type="button">Add note</button>
        </div>
      </div>
      <div class="form-group">
        <label>Ingredients</label>
        <div>
          <button class="btn btn-success add-ingredient" type="button">Add ingredient</button>
        </div>
      </div>
      <div class="form-group">
        <label>Directions</label>
        <div>
          <button class="btn btn-success add-direction" type="button">Add direction</button>
        </div>
      </div>
      <div class="form-row">
        <div class="col-8">
          <input type="submit" name="save" value="Save Recipe" class="btn btn-primary btn-block">
        </div>
        <div class="col-4">
          <input type="submit" name="save_and_add" value="Save and add another" class="btn btn-primary btn-block">
        </div>
      </div>
    </form>

    <!-- Form fields that get added on click -->
    <div class="d-none">
      <div class="input-group mb-3" id="note-template">
        <input type="text" class="form-control" name="notes" placeholder="Note">
        <div class="input-group-append">
          <button class="btn btn-danger remove" type="button"><i class="fas fa-minus"></i></button>
        </div>
      </div>
    </div>

    <div class="d-none">
      <div class="input-group mb-3" id="ingredient-template">
        <input type="text" class="form-control" name="ingredients" placeholder="Ingredient">
        <div class="input-group-append">
          <button class="btn btn-danger remove" type="button"><i class="fas fa-minus"></i></button>
        </div>
      </div>
    </div>

    <div class="d-none">
      <div class="input-group mb-3" id="direction-template">
        <input type="text" class="form-control" name="directions" placeholder="Direction">
        <div class="input-group-append">
          <button class="btn btn-danger remove" type="button"><i class="fas fa-minus"></i></button>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

saltToTaste/templates/index.html
{% extends "layout.html" %}

{% block title_container %}
<title>Salt To Taste</title>
{% endblock %}

{% block body_container %}
<div class="container-fluid mt-1">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-4 no-gutters">
    {% for recipe in recipes %}
    <div class="col">
      <div class="bg-light mb-1 mr-1 rounded recipe-card" style="background-image: linear-gradient(to bottom, rgba(255,255,255,0), rgba(255,255,255,0), rgba(0,0,0,1)), url('{% if recipe.image_path %}{{ url_for('main.image_path', filename=recipe.image_path) }}{% endif %}');">
        <div class="d-flex flex-column justify-content-end h-100 rounded recipe-card-content">
          <div class="pt-1 px-1 recipe-card-title">
            <a href="{{ url_for('main.recipe', recipe_link=recipe.title_formatted) }}" class="stretched-link text-decoration-none">
              <p class="m-0 p-0 text-decoration-none text-white clampThis">{{ recipe.title }}</p>
            </a>
          </div>
          <div class="ml-1 mb-1 recipe-card-tags">
            {% for tag in recipe.tags %}
            <a onclick="tagSearch('tag:{{ tag }}')" href="#">
              <span class="px-1 rounded recipe-card-tag {{ tag | replace (' ', '-') }}">
                {% if tag == 'vegetarian' %}
                <i class="fas fa-leaf"></i> {{ tag.title() }}
                {% elif tag == 'quick meal' %}
                <i class="fas fa-stopwatch"></i> {{ tag.title() }}
                {% else %}
                  {{ tag.title() }}
                {% endif %}
              </span>
            </a>
            {% endfor %}
            &nbsp;
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

saltToTaste/templates/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Salt To Taste</title>
    <link rel="shortcut icon" href="/static/images/favicon/favicon.ico">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
    <link rel="stylesheet" href="/static/css/selectize.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/salt_to_taste.css">
    <script src="/static/js/font-awesome.all.min.js"></script>
    <script src="/static/js/jquery-3.4.1.min.js"></script>
    <script src="/static/js/bootstrap.bundle.js"></script>
    <script src="/static/js/selectize.js"></script>
  </head>
  <body>
    <div class="body-container">
      <div class="login-container">
        <div class="login-header">
          <img class="login-image" src="{{ url_for('static', filename='logo/logo.png') }}">
        </div>
        <div class="login-body">
          <h2 class="text-center login-title">Log in</h2>
          <div class="login-alert">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <div class="alert alert-danger" role="alert">
                  {{ messages[0] }}
                </div>
              {% endif %}
            {% endwith %}
          </div>
          <div class="login-form">
              <form action="/login" method="post">
                  <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Username" required="required">
                  </div>
                  <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Password" required="required">
                  </div>
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Log in</button>
                  </div>
                  <label class="pull-left checkbox-inline"><input type="checkbox" name="remember"> Remember me</label>
              </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

saltToTaste/templates/recipe.html
{% extends "layout.html" %}

{% block title_container %}
<title>{{ recipe.title }} | Salt To Taste</title>
{% endblock %}

{% block body_container %}
<div class="container mt-1">
  <div class="row pb-2 row-cols-1 row-cols-md-2 no-gutters">
    <div class="col pr-0 pr-md-2 order-2 order-md-1">
      <div class="recipe-details-title">
        {{ recipe.title }}
        <a class="recipe-details-download" href="{{ url_for('main.download_recipe', filename=recipe.filename) }}" title="Download recipe">
          <i class="fas fa-file-download fa-xs"></i>
        </a>
      </div>
      {% if recipe.tags %}
      <div class="py-2 recipe-details-tags">
        {% for tag in recipe.tags %}
          <a onclick="tagSearch('tag:{{ tag }}')" href="/">
            <span class="px-1 rounded recipe-details-tag {{ tag | replace (' ', '-') }}">
              {% if tag == 'vegetarian' %}
                <i class="fas fa-leaf"></i> {{ tag.title() }}
              {% elif tag == 'quick meal' %}
                <i class="fas fa-stopwatch"></i> {{ tag.title() }}
              {% else %}
                {{ tag.title() }}
              {% endif %}
            </span>
          </a>
        {% endfor %}
      </div>
      {% endif %}
      {% if recipe.ready or recipe.servings or recipe.calories %}
      <div class="row py-2 text-center no-gutters border-top recipe-details-section-info">
        {% if recipe.ready %}
        <div class="col info-item">
          <i class="fas fa-clock fa-2x info-item-icon"></i>
          <div class='py-1 info-item-heading'>Time</div>
          <div class="info-item-value">
            {{ recipe.ready }}
          </div>
        </div>
        {% endif %}
        {% if recipe.servings %}
        <div class="col info-item">
          <i class="fas fa-utensils fa-2x info-item-icon"></i>
          <div class='py-1 info-item-heading'>Servings</div>
          <div class="info-item-value">
            {{ recipe.servings }}
          </div>
        </div>
        {% endif %}
        {% if recipe.calories %}
        <div class="col info-item">
          <i class="fas fa-fire fa-2x info-item-icon"></i>
          <div class='py-1 info-item-heading'>Nutrition</div>
          <div class="info-item-value">
            {{ recipe.calories }} calories
          </div>
        </div>
        {% endif %}
      </div>
      {% endif %}
      {% if recipe.description %}
      <div class="py-2 border-top recipe-details-description">
        {{ recipe.description }}
      </div>
      {% endif %}
      {% if recipe.notes %}
      <div class="row no-gutters pt-2 border-top recipe-details-section-notes">
        <div class="col-12 details-section-title">
          Notes
        </div>
        <ul class="col-12 row no-gutters pt-2 notes-list">
          {% for note in recipe.notes %}
            {% if note != '' %}
            <li class="col-12 col-md-6 notes-list-item">{{ note }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
      {% endif %}
    </div>
    <div class="col order-1 order-md-2 rounded recipe-details-image" style="background-image: url('{{ url_for('main.image_path', filename=recipe.image_path) }}')">

    </div>
  </div>
  {% if recipe.ingredients %}
  <div class="row no-gutters py-2 border-top recipe-details-section-ingredients">
    <div class="col-12 details-section-title">
      Ingredients
    </div>
    <ul class="col-12 row row-cols-1 row-cols-md-2 row-cols-lg-3 pt-2 ingredients-list">
      {% for ingredient in recipe.ingredients %}
        {% if ingredient != '' %}
        <li class="col py-1 ingredients-list-item">{{ ingredient }}</li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
  {% endif %}
  {% if recipe.directions %}
  <div class="row no-gutters py-2 border-top recipe-details-section-directions">
    <div class="col-12 details-section-title">
      Directions
    </div>
    <div class="col-12 row row-cols-1 row-cols-md-2 row-cols-lg-3 no-gutters directions-list">
      {% for direction in recipe.directions %}
      <div class="col pr-2 pt-2">
        <div class="p-3 h-100 border rounded directions-item">
          <div class="pb-2 border-bottom directions-item-title">
            Step {{ loop.index }}
          </div>
          <div class="pt-2 directions-item-content">
            {{ direction }}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

saltToTaste/templates/settings.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="/static/favicon/favicon.ico">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
    <link rel="stylesheet" href="/static/css/selectize.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/salt_to_taste.css">

    <title>Hello, world!</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="settings-header">
            Settings
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <div class="list-group" id="list-tab" role="tablist">
            <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">General</a>
            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Info</a>
          </div>
        </div>
        <div class="col-md-9">
          <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
              <form>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="api_enabled" name="api_enabled" value="1" checked="" data-parsley-multiple="api_enabled" data-parsley-id="149"> Enable API
                    </label>
                    <p class="help-block">Allow remote applications to interface with Tautulli.</p>
                </div>
                <div id="apioptions" style="overflow: hidden;">
                    <div class="form-group">
                        <label for="api_key">API key</label>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="input-group">
                                    <input class="form-control" type="text" name="api_key" id="api_key">
                                    <span class="input-group-btn">
                                        <button class="btn btn-form" type="button" id="generate_api">Generate</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
            <div class="tab-pane" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">Test 2</div>
            <div class="tab-pane" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">Test 3</div>
            <div class="tab-pane" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">Test 4</div>
          </div>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="/static/js/font-awesome.all.min.js"></script>
    <script src="/static/js/jquery-3.4.1.min.js"></script>
    <script src="/static/js/bootstrap.bundle.js"></script>
    <script src="/static/js/selectize.js"></script>
  </body>
</html>

saltToTaste/templates/signup.html
{% extends "layout.html" %}

{% block title_container %}
  <title>Salt To Taste</title>
{% endblock %}

{% block body_container %}
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="alert alert-danger" role="alert">
        {{ messages[0] }}
      </div>
    {% endif %}
  {% endwith %}
  <table>
    <tr>
      <th>Username</th>
      <th>Role</th>
    </tr>
    {% if users %}
      {% for user in users %}
      <tr>
        <td>{{ user.username }}</td>
        <td>{{ user.role }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td>-</td>
        <td>-</td>
      </tr>
    {% endif %}
  </table>
  <form action="/signup" method="post">
    Add user:
    <input type="text" name="username" placeholder="username">
    <input type="password" name="password" placeholder="password">
    <select name="role">
      {% if users %}
        <option value="read-only">Read-Only</option>
        <option value="admin">Admin</option>
      {% else %}
        <option value="owner">Owner</option>
        <option value="read-only" disabled>Read-Only</option>
        <option value="admin" disabled>Admin</option>
      {% endif %}
    </select>
    <input type="submit">
  </form>
  <form class="" action="/signup" method="post">
    Require account to access: <input type="checkbox" name="loginToView">
    <input type="submit" value="Save">
  </form>
  </form>
{% endblock %}